# request for Wilder

GET http://localhost:5000/api/Wilder/1
Content-Type: application/json

###
GET http://localhost:5000/api/Wilder
Content-Type: application/json

###
POST http://localhost:5000/api/Wilder
Content-Type: application/json

{
     "name": "other",
     "city": "city",

}

###
PUT http://localhost:5000/api/Wilder/2
Content-Type: application/json

{
     "name": "Emeric",
     "city": "Strasbourg" 
}

###
DELETE http://localhost:5000/api/Wilder/3
Content-Type: application/json


# request for skill

###
GET http://localhost:5000/api/Skill/2
Content-Type: application/json

###
GET http://localhost:5000/api/Skill
Content-Type: application/json

###
POST http://localhost:5000/api/Skill
Content-Type: application/json

{
     "name": "React" 
}

###
PUT http://localhost:5000/api/Skill/8
Content-Type: application/json

{
     "name": "Twig" 
}

###
DELETE http://localhost:5000/api/Skill/8
Content-Type: application/json


# Requête for Grade

###
GET http://localhost:5000/api/Grade/1
Content-Type: application/json

###
GET http://localhost:5000/api/Grade
Content-Type: application/json

###
POST http://localhost:5000/api/Grade
Content-Type: application/json

{
     "grade": 10,
     "skill": "React",
     "wilder": "Marie Moulon"
}

# marche pas !
###
PUT http://localhost:5000/api/Grade/4
Content-Type: application/json

{
     "grade": 1,
     "skill": "React",
     "wilder": "Marie Moulon"
}

###
DELETE http://localhost:5000/api/Grade/1
Content-Type: application/json

###

POST http://localhost:5000/api/avatar
