# request for Wilder
POST http://localhost:5000/api/Wilder
Content-Type: application/json

{
     "name": "other",
     "city": "city" 
}

###
GET http://localhost:5000/api/Wilder/1
Content-Type: application/json
###
GET http://localhost:5000/api/Wilder
Content-Type: application/json
###
PUT http://localhost:5000/api/Wilder/1
Content-Type: application/json

{
     "name": "jeanne",
     "city": "Trois" 
}

###
DELETE http://localhost:5000/api/Wilder/3
Content-Type: application/json


# request for skill
###
POST http://localhost:5000/api/Skill
Content-Type: application/json

{
     "name": "cdfsffg" 
}

###
GET http://localhost:5000/api/Skill/2
Content-Type: application/json
###
GET http://localhost:5000/api/Skill
Content-Type: application/json
###
PUT http://localhost:5000/api/Skill/8
Content-Type: application/json

{
     "name": "Twig" 
}

###
DELETE http://localhost:5000/api/Skill/8
Content-Type: application/json


# Requête for Grade

###
GET http://localhost:5000/api/Grade
Content-Type: application/json

###
POST http://localhost:5000/api/Grade
Content-Type: application/json

{
     "grade": 10,
     "skill": "PHP",
     "wilder": "jean"
}

###
DELETE http://localhost:5000/api/Grade/4
Content-Type: application/json

###
GET http://localhost:5000/api/Grade/5
Content-Type: application/json

###
PUT http://localhost:5000/api/Grade/1
Content-Type: application/json

{
     "grade": 7,
     "skill": "JavaScript",
     "wilder": "jeanne"
}