services:

  front:
    build: ./front
    volumes:
      - ./front/src:/app/src
    ports:
      - 3000:3000

  back:
    build: ./back
    volumes:
      - ./back/src:/app/src
    ports:
      - 5000:5000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mdpDbPostgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
