POST http://localhost:3000/api/Wilder
Content-Type: application/json

{
     "name": "other" 
}

###
GET http://localhost:3000/api/Wilder/1
Content-Type: application/json
###
GET http://localhost:3000/api/Wilder
Content-Type: application/json
###
PUT http://localhost:3000/api/Wilder/5
Content-Type: application/json

{
     "name": "jeanne" 
}

###
DELETE http://localhost:3000/api/Wilder/8
Content-Type: application/json

###
POST http://localhost:3000/api/Wilder/1/Skill/2


# request for skills
###
POST http://localhost:3000/api/Skills
Content-Type: application/json

{
     "name": "C#" 
}

###
GET http://localhost:3000/api/Skills/2
Content-Type: application/json
###
GET http://localhost:3000/api/Skills
Content-Type: application/json
###
PUT http://localhost:3000/api/Skills/7
Content-Type: application/json

{
     "name": ".NetCore" 
}

###
DELETE http://localhost:3000/api/Skills/5
Content-Type: application/json